### ISSUE TITLE
Add how to edit information

### ISSUE THREAD

**Issue by bshouse** [Colorado-CompSci-Ugrad/Colorado-CompSci-Ugrad.github.io#3]
Training on how to edit/contribute to the documentation

**Comment by bshouse** [comment]
Encourage students to fork / pull request

**Comment by dirkcgrunwald** [comment]
I added material at https://csel.cs.colorado.edu/update_this_site.html and point them to the issue list

**Comment by bshouse** [comment]
Thank you Dirk!
